Nicolas dev
NicolasAMontanez98/MercaShop pull request #17
Opened 2020-09-09 14:48 UTC by NicolasAMontanez98

Se agregó la vista de perfil, el model de las ordenes, y se eliminaron los comentarios.

2020-09-09 15:11 UTC, johnuribe17 approved these changes

2020-09-09 22:38 UTC, simonhoyos requested changes

2020-09-09 22:38 UTC, simonhoyos commented on Backend/src/models/order.model.js
> +const orderItemSchema = new Schema({
Alguna preferencia para manejar los esquemas de está forma vs crear diferentes modelos y referenciarlos?

2020-09-09 22:38 UTC, simonhoyos commented on Frontend/mercashop/src/components/ShowProducts.js
> +    return () => {};
Este return no está haciendo nada entonces se puede borrar

2020-09-09 22:38 UTC, simonhoyos commented on Frontend/mercashop/src/pages/ProductDetail.js
> +    return () => {};
lo mismo que el return anterior

2020-09-09 22:38 UTC, simonhoyos commented on Frontend/mercashop/src/pages/RegisterCostumer.js
> +    return () => {};
lo mismo

2020-09-09 22:38 UTC, simonhoyos commented on Frontend/mercashop/src/pages/RegisterProvider.js
> +    return () => {}
lo mismo

2020-09-09 22:38 UTC, simonhoyos commented on Frontend/mercashop/src/pages/login.js
> +    return () => {};
lo mismo

2020-09-09 22:38 UTC, simonhoyos commented on Frontend/mercashop/src/pages/Profile.js
> +    <div className="container">
Estos htmls tan largos pueden ser un indicador que necesitamos dividir en varios componentes

2020-09-10 17:25 UTC, jaimecabrera911 approved these changes

2020-09-10 17:38 UTC, merged