Se agregaron las funcionalidades de la orden, también los pagos, la p…
NicolasAMontanez98/MercaShop pull request #19
Opened 2020-09-16 02:01 UTC by NicolasAMontanez98

…ágina de shipping para pagos para confirmar la orden, se arreglaron estilos en la pagina inicial, y en el header

2020-09-16 03:31 UTC, johnuribe17 approved these changes

2020-09-16 17:26 UTC, simonhoyos requested changes

2020-09-16 17:26 UTC, simonhoyos commented on Backend/src/models/orderItem.model.js
> +// const orderItemSchema = new Schema({
borrar comentarios

2020-09-16 17:26 UTC, simonhoyos commented on Frontend/mercashop/.env
> +REACT_APP_EPAYCO_PUBLIC_KEY=1d68eea9a55b4dafea9bbe355dbf37a5
Ojo con esta información. El archivo de la variables de entorno lo debes agregar al gitignore y borrar este archivo con el comando `git rm --cached .env`

2020-09-16 17:26 UTC, simonhoyos commented on Frontend/mercashop/src/pages/Shipping.js
> +export default function Shipping() {
Este componente no está haciendo nada. Lo podrías dejar por fuera del PR

2020-09-16 17:26 UTC, simonhoyos commented on Frontend/mercashop/src/store/actions/orderAction.js
> +    console.log('la orden mi rey', order)
Borrar todos los console.logs

2020-09-16 17:36 UTC, NicolasAMontanez98 commented on Backend/src/models/orderItem.model.js
> +// const orderItemSchema = new Schema({
Ya se hicieron los cambios

2020-09-16 17:36 UTC, NicolasAMontanez98 commented on Frontend/mercashop/.env
> +REACT_APP_EPAYCO_PUBLIC_KEY=1d68eea9a55b4dafea9bbe355dbf37a5
Ya se hicieron los cambios

2020-09-16 17:38 UTC, NicolasAMontanez98 commented on Frontend/mercashop/src/pages/Shipping.js
> +export default function Shipping() {
Ya se hicieron los cambios

2020-09-16 17:38 UTC, NicolasAMontanez98 commented on Frontend/mercashop/src/store/actions/orderAction.js
> +    console.log('la orden mi rey', order)
Ya se hicieron los cambios

2020-09-16 22:04 UTC, simonhoyos approved these changes

2020-09-16 22:48 UTC, simonhoyos approved these changes

2020-09-17 03:07 UTC, jaimecabrera911 approved these changes

2020-09-17 03:57 UTC, merged