Se muestran las ordenes pagas desde el perfil del proveedor y corrigi…
NicolasAMontanez98/MercaShop pull request #25
Opened 2020-09-21 19:45 UTC by NicolasAMontanez98

- Se muestran las ordenes pagadas desde el perfil del proveedor
![Ordenes pagadas proveedor](https://user-images.githubusercontent.com/48807699/93813696-1b435180-fc19-11ea-9d6c-c226dea4bf4a.gif)

2020-09-21 20:25 UTC, johnuribe17 approved these changes

2020-09-22 16:39 UTC, simonhoyos requested changes

2020-09-22 16:39 UTC, simonhoyos commented on Frontend/mercashop/src/pages/OrdersProfileProvider.js
> +          console.log(data)
Puedes borrar este console.log

2020-09-22 16:45 UTC, NicolasAMontanez98 commented on Frontend/mercashop/src/pages/OrdersProfileProvider.js
> +          console.log(data)
Listo, si señor

2020-09-22 23:33 UTC, simonhoyos approved these changes

2020-09-23 00:09 UTC, jaimecabrera911 approved these changes

2020-09-23 00:13 UTC, merged