Implementar node mailer
NicolasAMontanez98/MercaShop pull request #26
Opened 2020-09-25 19:28 UTC by NicolasAMontanez98

- Se agregó y implementó nodemailer
- Se implementó la confirmación de correo en el registro
![image](https://user-images.githubusercontent.com/48807699/94307199-f52ff100-ff39-11ea-8ce8-d8e3dd79ae46.png)

- Alerta en el perfil en caso de que el usuario no confirme su correo
![image](https://user-images.githubusercontent.com/48807699/94307887-3543a380-ff3b-11ea-8ca8-4e101ed03009.png)

- Que redirecciona a la página de la tienda, activar cuenta
![Confirmación de correo](https://user-images.githubusercontent.com/48807699/94307651-d0884900-ff3a-11ea-81c3-d7bc0648ea9e.gif)

2020-09-25 19:34 UTC, johnuribe17 approved these changes

2020-09-27 23:19 UTC, simonhoyos requested changes

2020-09-27 23:19 UTC, simonhoyos commented on .vscode/settings.json
> +    "compile-hero.disable-compile-files-on-did-save-code": true
Este archivo son configuraciones locales de tu vscode. Puedes agregar la carpeta .vscode al .gitignore y removerla todos los archivos conrriendo el comando `git rm --cached .vscode`

2020-09-27 23:19 UTC, simonhoyos commented on Frontend/mercashop/src/pages/RegisterCostumer.js
> +    console.log(
REmover los console.logs de este archivo

2020-09-28 00:20 UTC, NicolasAMontanez98 commented on .vscode/settings.json
> +    "compile-hero.disable-compile-files-on-did-save-code": true
Aaaaaaa listo Simón, gracias, no tenía ni idea de que era eso, de pronto le di una opción y no me di cuenta

2020-09-28 01:03 UTC, NicolasAMontanez98 commented on Frontend/mercashop/src/pages/RegisterCostumer.js
> +    console.log(
Listo, ya lo hago

2020-09-28 16:26 UTC, simonhoyos approved these changes

2020-09-28 19:04 UTC, jaimecabrera911 approved these changes

2020-09-28 19:04 UTC, jaimecabrera911 approved these changes

2020-09-28 20:36 UTC, merged