agrega Cloudinary
NicolasAMontanez98/MercaShop pull request #27
Opened 2020-09-29 02:47 UTC by johnuribe17

Este PR es para poder adelantar en otras funcionalidades, falta corregir la URL de Cloudinary y borrar los comentarios,

2020-09-29 03:08 UTC, NicolasAMontanez98 approved these changes

2020-09-29 17:27 UTC, jaimecabrera911 approved these changes

2020-09-29 17:28 UTC, jaimecabrera911 approved these changes

2020-09-29 18:28 UTC, simonhoyos requested changes

2020-09-29 18:28 UTC, simonhoyos commented on Backend/src/app.js
> +  console.log(url);
borrar console.logs

2020-09-29 18:28 UTC, simonhoyos commented on Backend/src/controllers/provider.controller.js
> +    // console.log(req.params.id)
borrar comentarios

2020-09-29 18:28 UTC, simonhoyos commented on Backend/src/utils/middlewares.js
> +
Este middleware solo lo van a usar para subir una imagen? Qué pasa si al editar no subimos imagenes?

2020-09-29 19:30 UTC, johnuribe17 commented on Backend/src/utils/middlewares.js
> +
Por el momento solo sería para subir la imagen, los campos del formulario se guardan con otra petición que no usa este middleware, igual voy a trabajar en la actualización de productos y puede que en ese caso si sea necesario utilizarlo.

2020-09-29 19:43 UTC, johnuribe17 commented on Backend/src/app.js
> +  console.log(url);
Listo

2020-09-29 19:43 UTC, johnuribe17 commented on Backend/src/controllers/provider.controller.js
> +    // console.log(req.params.id)
Listo

2020-09-30 00:25 UTC, simonhoyos commented on Backend/src/utils/middlewares.js
> +
Listo ten en cuenta entonces que si en el futuro quieres usar este middleware para cualquier otro endpoint no va a funcionar si no se sube ninguna imagen porque el next solo se ejecuta al terminar de subir la primera imagen. Tampoco va a funcionar para casos en los que se suban varias imagenes

2020-09-30 00:26 UTC, simonhoyos approved these changes

2020-09-30 01:23 UTC, merged