Nicolas dev
NicolasAMontanez98/MercaShop pull request #4
Opened 2020-08-27 22:33 UTC by NicolasAMontanez98

Agregar carpeta backend con controllers, models, routes, conexión a base de datos, y algunos cambios como el icono al frontend, al proyecto base.

2020-08-28 01:26 UTC, johnuribe17 approved these changes

2020-08-31 10:23 UTC, simonhoyos requested changes

2020-08-31 10:23 UTC, simonhoyos commented on Backend/src/models/product.model.js
> +    name: String,
Sería bueno agregar validaciones

2020-08-31 10:23 UTC, simonhoyos commented on Backend/src/routes/home.js
> +router.routes('/')
Si esta ruta no se va a usar todavía mejor borrar el código

2020-08-31 10:23 UTC, simonhoyos commented on Backend/src/routes/login.js
> +const router = Router();
se pueden crear las rutas en el momento que sea requerido. Esto es código muerto

2020-08-31 10:23 UTC, simonhoyos commented on Backend/src/routes/register-client.js
> +const router = Router();
lo mismo

2020-08-31 13:10 UTC, NicolasAMontanez98 commented on Backend/src/routes/register-client.js
> +const router = Router();
entendido, ya se corrigió.

2020-08-31 13:10 UTC, NicolasAMontanez98 commented on Backend/src/routes/login.js
> +const router = Router();
entendido, ya se corrigió.

2020-08-31 13:10 UTC, NicolasAMontanez98 commented on Backend/src/routes/home.js
> +router.routes('/')
entendido, ya se corrigió.

2020-08-31 13:29 UTC, NicolasAMontanez98 commented on Backend/src/models/product.model.js
> +    name: String,
Entendido, hoy los agregamos.

2020-09-01 10:03 UTC, simonhoyos commented on Backend/src/database.js
> +const URI = process.env.MONGODB_URI
Puedes simplificar un poco este código con `process.env.MONGO_URI || mongodb://loclahost:27017/databasetest` ya acá le está diciendo al código que le asigne `MONGO_URI` si existe y si no pues que asigne la otra

2020-09-01 10:04 UTC, simonhoyos approved these changes

2020-09-01 10:06 UTC, simonhoyos commented
Trata de mantener los PR pequeños y más especificos. La idea es crear una rama, completar una tarea, hacer merge del PR, borrar la rama, y volver a empezar. Cuando hay muchos cambios en un PR se vuelve difícil de seguir

2020-09-01 18:10 UTC, jaimecabrera911 approved these changes

2020-09-01 18:10 UTC, merged

2020-09-01 18:10 UTC, jaimecabrera911 approved these changes